### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by lukasmartinelli** [boundlessgeo/ol-mapbox-gl-style#1]
I know it this is still not production ready but  could you publish `ol-mapbox-gl-style` to npm?

BTW. I am really amazed by this project. Hope to contribute. This could be the corner stone of building an style editor for OL3. https://github.com/maputnik/editor/issues/7

**Comment by ahocevar** [comment]
Thanks for your interest and the positive feedback @lukasmartinelli. I'll publish to npm later this week.

**Comment by ahocevar** [comment]
Published. Disclaimer: expect API changes before v1.0.0 is reached.
