### ISSUE TITLE
Problem styling a point feature with "icon-image" via "getStyleFunction"

### ISSUE THREAD

**Issue by chrismayer** [boundlessgeo/ol-mapbox-gl-style#4]
I am trying to style a point features in an ``ol.layer.Vector`` with a simple ``icon-image`` defined in a Mapbox GL Style. Therefore I am executing the API function ``getStyleFunction``, which raises an exception:

In line [408](https://github.com/boundlessgeo/ol-mapbox-gl-style/blob/master/index.js#L408) of the index script the function ``fromTemplate`` is executed which leads to the mentioned exception. The regex used in this function does not match with the expression in the style property ``icon-image`` and returns ``null`` (see [here](https://github.com/boundlessgeo/ol-mapbox-gl-style/blob/master/index.js#L215) ). Which kind of expression is expected here? Has the regex to be adapted or is the style description (see code below) incorrect although it is exported from Mapbox studio? 

The style object used looks like this:

```json
{
   "id": "foo",
   "type": "symbol",
   "source": "composite",
   "source-layer": "foolayer",
   "interactive": true,
   "filter": [
     "all",
     [
       "==",
       "$type",
       "Point"
     ],
     [
       "all",
       [
         "==",
         "propertyFoo",
         2
       ]
     ]
   ],
   "layout": {
     "icon-image": "dam-15",
     "visibility": "visible"
   }
}
```

**Comment by chrismayer** [comment]
One more information:

When I skip the ``fromTemplate`` function by setting ``icon = iconImage;`` the script runs without any problems.

**Comment by ahocevar** [comment]
This is probably a bug. The regex is confused when the 'icon-image' does not contain a `{field}`.

**Comment by ahocevar** [comment]
I just pushed 86f8a09, which should fix the issue. Can you please verify?

**Comment by chrismayer** [comment]
Correct @ahocevar, 86f8a09 fixes the issue. 

Thanks for your fast reaction and in general for this great library!
